### ISSUE TITLE
empty content file for em.test

### ISSUE THREAD

**Issue by Olgalex** [LLazyEmail/markdown-regex#181] opened 2022-08-01 13:41 UTC
**Describe the bug**
expect(recieved).toBe(expected) !== object is equality

**To Reproduce**
Go to RegEx: `REGEXP_EM`

**Expected result**
expect(recieved).toBe(expected) === object is equality

**Actual result**
expect(recieved).toBe(expected) !== object is equality

**Additional context**
content.md is empty
https://github.com/LLazyEmail/markdown-regex/blob/main/tests/em/content.md

**Comment by atherdon** [comment] 2022-09-05 14:38
i thinks it's a duplicate of #215, right? can i close this task

**Comment by Olgalex** [comment] 2022-09-05 16:12
yes, you can close this task

**Comment by atherdon** [comment] 2022-09-05 16:34
thank you, closing then

**Closed by atherdon** 2022-09-05 16:34 UTC
Labels: bug
